services:
  # Nginx reverse proxy - standalone service
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # HTTPS port
    volumes:
      - ./nginx-api-only.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cache:/var/cache/nginx
      # SSL certificates from Let's Encrypt
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - NGINX_HOST=server.epicrunze.com
      - NGINX_PORT=80
    networks:
      - evocable-network
    depends_on: []  # No direct dependencies since services run separately

volumes:
  nginx_logs:
  nginx_cache:

networks:
  evocable-network:
    external: true
    name: evocable-network 